# Generated by Django 5.1.1 on 2025-10-01 19:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de madera')),
                ('descripcion', models.TextField(help_text='Descripción detallada del tipo de madera', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de madera',
                'verbose_name_plural': 'Tipos de madera',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_empresa'],
                'indexes': [models.Index(fields=['nombre_empresa'], name='api_cliente_nombre__63305b_idx'), models.Index(fields=['correo_electronico'], name='api_cliente_correo__e1a5c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre completo del conductor', max_length=100, verbose_name='Nombre completo')),
                ('licencia_conducir', models.CharField(help_text='Número de licencia de conducir', max_length=50, unique=True, verbose_name='Licencia de conducir')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['licencia_conducir'], name='api_conduct_licenci_94a4b3_idx'), models.Index(fields=['nombre'], name='api_conduct_nombre_6ebffe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(help_text='Placa del camión', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener formato válido (ej: ABC1234)', regex='^[A-Z]{2,4}\\d{2,4}$')], verbose_name='Placa')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('capacidad_carga', models.FloatField(help_text='Capacidad máxima de carga en toneladas', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Capacidad de carga (toneladas)')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones', to='api.conductor', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.FloatField(help_text='Cantidad de unidades de madera', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Cantidad (unidades)')),
                ('peso', models.FloatField(help_text='Peso total de la carga en toneladas', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Peso (toneladas)')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='api.camion', verbose_name='Camión')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='api.cliente', verbose_name='Cliente')),
                ('tipo_madera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='api.tipomadera', verbose_name='Tipo de madera')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['placa'], name='api_camion_placa_0dfefc_idx'),
        ),
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['-created_at'], name='api_carga_created_6d8fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['camion', 'cliente'], name='api_carga_camion__519bd2_idx'),
        ),
    ]
